[workspace]
resolver = "2"
members = ["core/adder", "calc", "core/differ", "extras/divide", "luckynum", "extras/product"]

[workspace.dependencies]
addition = {path="core/adder"}
substraction = {path = "core/differ"}