[package]
name = "calc"
version = "0.1.0"
edition = "2021"

[dependencies]
addition = {workspace = true}
substraction = {workspace = true}
divide = { path = "../extras/divide"}
product = {path = "../extras/product"}
luckynum = {path = "../luckynum"}
